name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.1.1

      - name: Format
        run: deno fmt --check

      - name: Build
        run: |
          deno run --unstable --allow-read --allow-write --allow-net https://deno.land/x/pagic@0.7.9/mod.ts build

      - name: Deploy
        if: |
          startsWith(matrix.os, 'ubuntu') &&
          github.ref == 'refs/heads/master' &&
          github.event_name == 'push' &&
          github.repository == 'denocn/deno_manual'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: manual.deno.js.cn
